# Default values for singleton chart
# This is a YAML-formatted file.

# Values for cert-manager subchart
cert-manager:
  installCRDs: true
  # Namespace configuration for cert-manager
  namespace: cert-manager
  # Additional cert-manager configuration can be added here

# Values for GitHub Actions Runner Controller
gha-runner-scale-set-controller:
  namespaceOverride: gh-arc-systems
  createNamespace: true 
