{{- if .Values.dockerRegistry.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalyst-singleton.fullname" . }}-docker-registry
  labels:
    {{- include "catalyst-singleton.labels" . | nindent 4 }}
    app.kubernetes.io/component: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "catalyst-singleton.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: docker-registry
  template:
    metadata:
      labels:
        {{- include "catalyst-singleton.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: "{{ .Values.dockerRegistry.image.repository }}:{{ .Values.dockerRegistry.image.tag }}"
          imagePullPolicy: {{ .Values.dockerRegistry.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.dockerRegistry.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v2/
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /v2/
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.dockerRegistry.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
              readOnly: true
            {{- if .Values.dockerRegistry.persistence.enabled }}
            - name: storage
              mountPath: {{ .Values.dockerRegistry.storage.filesystem.rootdirectory }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "catalyst-singleton.fullname" . }}-registry-config
        {{- if .Values.dockerRegistry.persistence.enabled }}
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "catalyst-singleton.fullname" . }}-docker-registry-storage
        {{- else }}
        - name: storage
          emptyDir: {}
        {{- end }}
      {{- with .Values.dockerRegistry.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dockerRegistry.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.dockerRegistry.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}