# Design Example: User-Managed Helm Deployment
# FR-ENV-014: Custom/External Helm Chart Support
# The user handles the entire Helm deployment.
# The operator applies the chart but allows full control via values.

apiVersion: catalyst.catalyst.dev/v1alpha1
kind: Project
metadata:
  name: custom-helm-project
spec:
  templates:
    # Production uses a custom chart from the user's repo
    deployment:
      type: helm
      path: charts/my-complex-app
      sourceRef: main-repo
      
      # User provides all values, Operator injects minimal or no defaults
      values:
        ingress:
          enabled: true
          className: nginx
          hosts:
            - host: my-app.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
        
        # User manages their own sidecars/deps in their chart
        postgresql:
          enabled: true
          auth:
            password: "secret-password"

    # Alternative: External Chart (Future/Design Idea)
    # Using a chart from an external repository
    deployment-external:
      type: helm
      # sourceRef is omitted or points to a source defining the helm repo?
      # Or we add a 'repository' field to the template.
      repository: https://charts.bitnami.com/bitnami
      chart: node
      version: 1.0.0
      values:
        replicaCount: 2
