{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.auth.existingSecret | default (printf "%s-database" (include "nextjs.fullname" .)) }}
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $postgresqlPassword := include "nextjs.postgresql.password" . }}
  {{- $postgresqlAdminPassword := include "nextjs.postgresql.adminPassword" . }}
  DATABASE_URL: {{ include "nextjs.database.url" . | b64enc }}
  {{ .Values.postgresql.auth.secretKeys.userPasswordKey }}: {{ $postgresqlPassword | b64enc }}
  {{ .Values.postgresql.auth.secretKeys.adminPasswordKey }}: {{ $postgresqlAdminPassword | b64enc }}
{{- end }}