{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nextjs.fullname" . }}-database
  labels:
    {{- include "nextjs.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $postgresqlPassword := include "nextjs.postgresql.password" . }}
  DATABASE_URL: {{ include "nextjs.database.url" . | b64enc }}
{{- end }}