apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-request-job-pod
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pull-request-job-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pull-request-job-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pull-request-job-pod
  namespace: default
roleRef:
  kind: Role
  name: pull-request-job-role
  apiGroup: rbac.authorization.k8s.io