name: Kind Cluster Testing

"on":
  pull_request:
    branches: [main, master]
    paths:
      - '.github/workflows/test.kind.yml'
      - 'charts/catalyst-singleton/**'
  workflow_dispatch:

jobs:
  kind-test:
    name: Test with Kind Cluster
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: test-cluster
          wait: 60s

      - name: Verify cluster with kubectl
        run: |
          # Verify that kubectl can communicate with the cluster
          echo "Checking cluster info..."
          kubectl cluster-info

          echo "Checking nodes..."
          kubectl get nodes

          echo "Checking namespaces..."
          kubectl get namespaces

          echo "Checking pods in kube-system..."
          kubectl get pods -n kube-system

          echo "Cluster verification completed successfully!"

      - name: Install catalyst-singleton with Docker registry
        run: |
          echo "Installing catalyst-singleton Helm chart with registry..."

          # Install the catalyst-singleton chart
          helm install catalyst-singleton ./charts/catalyst-singleton \
            --wait \
            --timeout=300s

          echo "Catalyst-singleton chart installed successfully!"
          kubectl get pods,svc -l app.kubernetes.io/name=catalyst-singleton

          # Set up port forwarding for registry access in background
          kubectl port-forward service/catalyst-singleton-docker-registry \
            5000:5000 &
          sleep 10

          # Test registry connectivity
          curl -f "http://localhost:5000/v2/" && echo "Registry is accessible!"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push web application to in-cluster registry
        run: |
          echo "Building and pushing web/Dockerfile to in-cluster registry..."

          # Build and push to the in-cluster registry
          docker build \
            --tag localhost:5000/catalyst-web:test \
            --file web/Dockerfile \
            web/

          # Push the image to the registry
          docker push localhost:5000/catalyst-web:test

          echo "Web application build and push completed successfully!"

          # Verify the image was pushed successfully
          echo "Verifying image push to registry..."
          curl -f "http://localhost:5000/v2/catalyst-web/tags/list" && \
            echo "Image successfully pushed and verified in registry!" || \
            echo "Warning: Could not verify image in registry, but push succeeded"

      - name: Test basic kubectl operations
        run: |
          # Create a test namespace
          kubectl create namespace test-namespace

          # Verify the namespace was created
          kubectl get namespace test-namespace

          # Create a simple pod
          kubectl run test-pod --image=nginx:alpine \
            --restart=Never -n test-namespace

          # Wait for pod to be ready
          kubectl wait --for=condition=Ready pod/test-pod \
            -n test-namespace --timeout=60s

          # Verify the pod is running
          kubectl get pods -n test-namespace

          # Clean up
          kubectl delete namespace test-namespace

          echo "Basic kubectl operations test completed successfully!"
