name: Test Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/actions/build-container/**'
  pull_request:
    paths:
      - 'web/**'
      - '.github/actions/build-container/**'

jobs:
  test-web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
      
      - name: Build Next.js
        run: npm run build

  integration:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalyst_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: integration-test-cluster
          wait: 60s

      - name: Export kubeconfig for integration tests
        run: |
          # Export base64 encoded kubeconfig for integration tests
          export KUBECONFIG_PRIMARY=$(kubectl config view --raw -o json | base64 -w 0)
          echo "KUBECONFIG_PRIMARY=$KUBECONFIG_PRIMARY" >> $GITHUB_ENV
          echo "Kubeconfig exported for integration tests"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run integration tests
        run: npm test
        env:
          NODE_ENV: test
          GITHUB_APP_ID: test-app-id
          GITHUB_WEBHOOK_SECRET: test-secret
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/catalyst_test
          KUBECONFIG_PRIMARY: ${{ env.KUBECONFIG_PRIMARY }}

  e2e:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: catalyst_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: cp .env.example .env

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: e2e-test-cluster
          wait: 60s

      - name: Export kubeconfig for E2E tests
        run: |
          # Export base64 encoded kubeconfig for E2E tests
          export KUBECONFIG_PRIMARY=$(kubectl config view --raw -o json | base64 -w 0)
          echo "KUBECONFIG_PRIMARY=$KUBECONFIG_PRIMARY" >> $GITHUB_ENV
          echo "Kubeconfig exported for E2E tests"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './web/package-lock.json'
      
      - name: Install dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(node -p "require('./package.json').devDependencies['@playwright/test'].replace('^', '')")" >> $GITHUB_OUTPUT

      - name: Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      
      - name: Run Playwright tests
        run: npm run test:e2e
        env:
          MOCKED: 1
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/catalyst_test
          KUBECONFIG_PRIMARY: ${{ env.KUBECONFIG_PRIMARY }}
      
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: ./web/playwright-report/
          retention-days: 30
      
      - name: Upload test screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-screenshots
          path: ./web/test-results/**/test-failed-*.png
          retention-days: 30
      
      - name: Upload test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-videos
          path: ./web/test-results/**/video.webm
          retention-days: 30

  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    outputs:
      image-tags: ${{ steps.build.outputs.image }}
      image-digest: ${{ steps.build.outputs.digest }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push container
        id: build
        uses: ./.github/actions/build-container
        with:
          registry: ghcr.io
          image: ${{ github.repository }}/web
          platforms: 'linux/amd64'

  preview-environment:
    needs: build-container
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: preview-cluster
          wait: 60s

      - name: Export kubeconfig for preview environment
        run: |
          # Export base64 encoded kubeconfig for preview environment
          export KUBECONFIG_PRIMARY=$(kubectl config view --raw -o json | base64 -w 0)
          echo "KUBECONFIG_PRIMARY=$KUBECONFIG_PRIMARY" >> $GITHUB_ENV
          echo "Kubeconfig exported for preview environment"

      - name: Set PR tag
        run: |
          echo "PR_TAG=pr-${{ github.event.number }}" >> $GITHUB_ENV
          echo "NAMESPACE=preview-pr-${{ github.event.number }}" >> $GITHUB_ENV

      - name: Create preview namespace
        run: |
          kubectl create namespace ${{ env.NAMESPACE }}

      - name: Deploy to Kind cluster using Helm chart
        run: |
          # Extract the pr tag from the built image
          FULL_IMAGE_TAG=$(echo '${{ needs.build-container.outputs.image-tags }}' | grep 'pr-' | head -n 1)
          if [ -z "$FULL_IMAGE_TAG" ]; then
            echo "No PR tag found in built images, using SHA tag as fallback"
            FULL_IMAGE_TAG=$(echo '${{ needs.build-container.outputs.image-tags }}' | head -n 1)
          fi
          
          echo "Deploying image: $FULL_IMAGE_TAG"
          echo "To namespace: ${{ env.NAMESPACE }}"
          
          # Extract repository and tag from the full image tag
          IMAGE_REPO=$(echo "$FULL_IMAGE_TAG" | cut -d':' -f1)
          IMAGE_TAG=$(echo "$FULL_IMAGE_TAG" | cut -d':' -f2)
          
          # Deploy using the nextjs Helm chart
          helm install web-preview-${{ github.event.number }} ./charts/nextjs \
            --namespace ${{ env.NAMESPACE }} \
            --set image.repository="$IMAGE_REPO" \
            --set image.tag="$IMAGE_TAG" \
            --set image.pullPolicy=IfNotPresent \
            --wait --timeout=300s

      - name: Verify deployment
        run: |
          kubectl wait --for=condition=available --timeout=300s deployment/web-preview-${{ github.event.number }}-nextjs -n ${{ env.NAMESPACE }}
          helm test web-preview-${{ github.event.number }} --namespace ${{ env.NAMESPACE }} 
