apiVersion: catalyst.catalyst.dev/v1alpha1
kind: Project
metadata:
  name: prebuilt-project
  namespace: catalyst-system
spec:
  sources:
    - name: app
      repositoryUrl: https://github.com/example/app.git
      branch: main

  templates:
    # "deployment" template uses a prebuilt image from registry
    deployment:
      type: helm
      path: charts/generic-app
      values:
        image:
          repository: ghcr.io/example/app
          pullPolicy: Always
          # 'tag' is omitted here; injected by Environment
