apiVersion: catalyst.catalyst.dev/v1alpha1
kind: Project
metadata:
  name: catalyst
  namespace: catalyst-system
spec:
  sources:
    - name: catalyst
      repositoryUrl: https://github.com/ncrmro/catalyst.git
      branch: main
  
  # Templates define how different environment types are deployed
  templates:
    # Development environment: Hot-reload, local values
    development:
      type: helm
      path: charts/catalyst
      sourceRef: catalyst
      values:
        environment: development
        replicaCount: 1
        image:
          pullPolicy: IfNotPresent
    
    # Deployment environment: Optimized, production values (used for Staging/Prod)
    deployment:
      type: helm
      path: charts/catalyst
      sourceRef: catalyst
      values:
        environment: production
        replicaCount: 2
        image:
          pullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 512Mi

  resources:
    defaultQuota:
      cpu: "4"
      memory: "8Gi"
